In [47]:
import numpy as np

rng = np.random.default_rng(1234)  # seed

class puzzleSolver:
    def __init__(self, m, n):
        self.m = m
        self.n = n    
        self.grid = np.arange(self.m*self.n)
        rng.shuffle(self.grid)
        self.grid.resize(self.m,self.n)
        self.goalState = np.arange(self.m*self.n)
        self.goalState.resize(self.m,self.n)
    def show(self):
        print(self.grid)
    def randomWalkStep(self):
        idxOld = np.where(self.grid == 0)
        mOld, nOld = idxOld
        idxNew = None
        isVerticalMove = rng.integers(0,2)
        if isVerticalMove == 1:
            mNew = mOld + self._getMove(mOld,self.m)
            idxNew = mNew, nOld
        elif isVerticalMove == 0:
            nNew = nOld + self._getMove(nOld,self.n)
            idxNew = mOld, nNew
        self.grid[idxOld] = self.grid[idxNew]
        self.grid[idxNew] = 0
    def _getMove(self,part,dim):
        if part == 0:
            return 1
        elif part == dim-1:
            return -1
        else:
            return rng.choice([-1,1])
    def isGoalState(self):
        if (self.grid == self.goalState).all():
            return True
        else:
            return False
    def run(self, method, maxCycle, showAt=-1):
        print('Initial grid:')
        self.show()
        for cycle in np.arange(1,maxCycle+1):
            self.randomWalkStep()
            if showAt > 0:
                if cycle%showAt == 0:
                    print('Grid in cycle', cycle,':')
                    self.show()
            if self.isGoalState():
                print('Done in cycle: ',cycle)
                self.show()
                return 
            if cycle == maxCycle:
                print('Reached max number of cycles(',maxCycle,'). Grid:')
                self.show()
    




puzzle = puzzleSolver(3,3)
puzzle.run('randomWalk', 1000000)

Initial grid:
[[7 8 5]
 [0 2 6]
 [4 1 3]]
Done in cycle:  136997
[[0 1 2]
 [3 4 5]
 [6 7 8]]
